spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//saichandkyama//Documents//Learning//config"
        git:
          uri: "https://github.com/saichandkyama/microservices-config.git"
          default-label: master
          clone-on-start: true
          force-pull: true
server:
  port: 8071

encrypt:
  key: YSjxiDjeBrZEwWSyY6mOUx11V8T6TooR